const invoiceData = [
  {
    status: "unpaid",
    date: "2023-03-17",
    invoiceNo: "34534",
    client: "Askon Tech Ltd",
    description: "Webpage design",
    statusText: "UNPAID",
    amount: "$500",
  },
  {
    status: "unpaid",
    date: "2023-03-18",
    invoiceNo: "34535",
    client: "Beta Solutions",
    description: "App development",
    statusText: "UNPAID",
    amount: "$1200",
  },
  {
    status: "paid",
    date: "2023-03-19",
    invoiceNo: "34536",
    client: "Dakoke Springs Ltd",
    description: "Landing page design",
    statusText: "PAID",
    amount: "$800",
  },
  {
    status: "paid",
    date: "2023-03-20",
    invoiceNo: "34537",
    client: "Dakoke Springs Ltd",
    description: "Landing page design",
    statusText: "PAID",
    amount: "$800",
  },
  {
    status: "unpaid",
    date: "2023-03-21",
    invoiceNo: "34538",
    client: "Dakoke Springs Ltd",
    description: "Landing page design",
    statusText: "UNPAID",
    amount: "$800",
  },
  {
    status: "unpaid",
    date: "2023-03-22",
    invoiceNo: "34539",
    client: "Dakoke Springs Ltd",
    description: "Landing page design",
    statusText: "UNPAID",
    amount: "$800",
  },
  {
    status: "unpaid",
    date: "2023-03-23",
    invoiceNo: "34540",
    client: "Dakoke Springs Ltd",
    description: "Landing page design",
    statusText: "UNPAID",
    amount: "$800",
  },
  {
    status: "paid",
    date: "2023-03-24",
    invoiceNo: "34541",
    client: "Dakoke Springs Ltd",
    description: "Landing page design",
    statusText: "PAID",
    amount: "$800",
  },
  {
    status: "unpaid",
    date: "2023-03-25",
    invoiceNo: "34542",
    client: "Dakoke Springs Ltd",
    description: "Landing page design",
    statusText: "UNPAID",
    amount: "$800",
  },
  {
    status: "paid",
    date: "2023-03-26",
    invoiceNo: "34543",
    client: "Dakoke Springs Ltd",
    description: "Landing page design",
    statusText: "PAID",
    amount: "$800",
  },
  {
    status: "paid",
    date: "2023-03-27",
    invoiceNo: "34544",
    client: "Dakoke Springs Ltd",
    description: "Landing page design",
    statusText: "PAID",
    amount: "$800",
  },

  // Add more invoices as needed
];

export default invoiceData;
