const expenses = [
  {
    _id: "1",
    date: "2023-01-15",
    type: "Office Supplies",
    vendor: "Vendor A",
    amount: 150,
    description: "Printer Ink",
    status: "Paid",
    payment_method: "Credit Card",
    payment_status: "Completed",
    transaction_id: "TX12345",
  },
  {
    _id: "2",
    date: "2023-02-20",
    type: "Software",
    vendor: "Vendor B",
    amount: 300,
    description: "Annual Subscription",
    status: "Paid",
    payment_method: "Bank Transfer",
    payment_status: "Completed",
    transaction_id: "TX12346",
  },
  {
    _id: "3",
    date: "2023-03-10",
    type: "Travel",
    vendor: "Vendor C",
    amount: 500,
    description: "Business Trip to NYC",
    status: "Paid",
    payment_method: "Credit Card",
    payment_status: "Completed",
    transaction_id: "TX12347",
  },
  {
    _id: "4",
    date: "2023-04-05",
    type: "Utilities",
    vendor: "Vendor D",
    amount: 200,
    description: "Electricity Bill",
    status: "Paid",
    payment_method: "Bank Transfer",
    payment_status: "Completed",
    transaction_id: "TX12348",
  },
  {
    _id: "5",
    date: "2023-05-25",
    type: "Maintenance",
    vendor: "Vendor E",
    amount: 250,
    description: "Office Cleaning",
    status: "Paid",
    payment_method: "Cash",
    payment_status: "Completed",
    transaction_id: "TX12349",
  },
  {
    _id: "6",
    date: "2023-06-15",
    type: "Office Supplies",
    vendor: "Vendor A",
    amount: 100,
    description: "Stationery",
    status: "Paid",
    payment_method: "Credit Card",
    payment_status: "Completed",
    transaction_id: "TX12350",
  },
  {
    _id: "7",
    date: "2023-07-18",
    type: "Software",
    vendor: "Vendor B",
    amount: 400,
    description: "Project Management Tool",
    status: "Paid",
    payment_method: "Bank Transfer",
    payment_status: "Completed",
    transaction_id: "TX12351",
  },
  {
    _id: "8",
    date: "2023-08-22",
    type: "Travel",
    vendor: "Vendor C",
    amount: 700,
    description: "Conference in LA",
    status: "Paid",
    payment_method: "Credit Card",
    payment_status: "Completed",
    transaction_id: "TX12352",
  },
  {
    _id: "9",
    date: "2023-09-10",
    type: "Utilities",
    vendor: "Vendor D",
    amount: 180,
    description: "Water Bill",
    status: "Paid",
    payment_method: "Bank Transfer",
    payment_status: "Completed",
    transaction_id: "TX12353",
  },
  {
    _id: "10",
    date: "2023-10-05",
    type: "Maintenance",
    vendor: "Vendor E",
    amount: 300,
    description: "HVAC Repair",
    status: "Paid",
    payment_method: "Cash",
    payment_status: "Completed",
    transaction_id: "TX12354",
  },
  {
    _id: "11",
    date: "2023-11-15",
    type: "Office Supplies",
    vendor: "Vendor A",
    amount: 120,
    description: "Paper and Toner",
    status: "Paid",
    payment_method: "Credit Card",
    payment_status: "Completed",
    transaction_id: "TX12355",
  },
  {
    _id: "12",
    date: "2023-12-20",
    type: "Software",
    vendor: "Vendor B",
    amount: 250,
    description: "Antivirus Software",
    status: "Paid",
    payment_method: "Bank Transfer",
    payment_status: "Completed",
    transaction_id: "TX12356",
  },
  {
    _id: "13",
    date: "2024-01-10",
    type: "Travel",
    vendor: "Vendor C",
    amount: 600,
    description: "Client Meeting in SF",
    status: "Paid",
    payment_method: "Credit Card",
    payment_status: "Completed",
    transaction_id: "TX12357",
  },
  {
    _id: "14",
    date: "2024-02-05",
    type: "Utilities",
    vendor: "Vendor D",
    amount: 210,
    description: "Gas Bill",
    status: "Paid",
    payment_method: "Bank Transfer",
    payment_status: "Completed",
    transaction_id: "TX12358",
  },
  {
    _id: "15",
    date: "2024-03-20",
    type: "Maintenance",
    vendor: "Vendor E",
    amount: 400,
    description: "Office Renovation",
    status: "Paid",
    payment_method: "Cash",
    payment_status: "Completed",
    transaction_id: "TX12359",
  },
  {
    _id: "16",
    date: "2024-04-10",
    type: "Office Supplies",
    vendor: "Vendor A",
    amount: 180,
    description: "Desk Chairs",
    status: "Paid",
    payment_method: "Credit Card",
    payment_status: "Completed",
    transaction_id: "TX12360",
  },
  {
    _id: "17",
    date: "2024-05-25",
    type: "Software",
    vendor: "Vendor B",
    amount: 350,
    description: "Design Software",
    status: "Paid",
    payment_method: "Bank Transfer",
    payment_status: "Completed",
    transaction_id: "TX12361",
  },
  {
    _id: "18",
    date: "2024-06-15",
    type: "Travel",
    vendor: "Vendor C",
    amount: 750,
    description: "Training in Chicago",
    status: "Paid",
    payment_method: "Credit Card",
    payment_status: "Completed",
    transaction_id: "TX12362",
  },
  {
    _id: "19",
    date: "2024-07-10",
    type: "Utilities",
    vendor: "Vendor D",
    amount: 190,
    description: "Internet Bill",
    status: "Paid",
    payment_method: "Bank Transfer",
    payment_status: "Completed",
    transaction_id: "TX12363",
  },
  {
    _id: "20",
    date: "2024-08-05",
    type: "Maintenance",
    vendor: "Vendor E",
    amount: 270,
    description: "Plumbing Repair",
    status: "Paid",
    payment_method: "Cash",
    payment_status: "Completed",
    transaction_id: "TX12364",
  },
  {
    _id: "21",
    date: "2024-09-15",
    type: "Office Supplies",
    vendor: "Vendor A",
    amount: 130,
    description: "Office Decor",
    status: "Paid",
    payment_method: "Credit Card",
    payment_status: "Completed",
    transaction_id: "TX12365",
  },
  {
    _id: "22",
    date: "2024-10-20",
    type: "Software",
    vendor: "Vendor B",
    amount: 280,
    description: "CRM Software",
    status: "Paid",
    payment_method: "Bank Transfer",
    payment_status: "Completed",
    transaction_id: "TX12366",
  },
  {
    _id: "23",
    date: "2024-11-10",
    type: "Travel",
    vendor: "Vendor C",
    amount: 800,
    description: "International Conference",
    status: "Paid",
    payment_method: "Credit Card",
    payment_status: "Completed",
    transaction_id: "TX12367",
  },
  {
    _id: "24",
    date: "2024-12-05",
    type: "Utilities",
    vendor: "Vendor D",
    amount: 220,
    description: "Heating Bill",
    status: "Paid",
    payment_method: "Bank Transfer",
    payment_status: "Completed",
    transaction_id: "TX12368",
  },
  {
    _id: "25",
    date: "2024-12-30",
    type: "Maintenance",
    vendor: "Vendor E",
    amount: 350,
    description: "Roof Repair",
    status: "Paid",
    payment_method: "Cash",
    payment_status: "Completed",
    transaction_id: "TX12369",
  },
];

export default expenses;
