"""changed payment modal to revenue modal

Revision ID: 4f687ccab0ad
Revises: 
Create Date: 2024-06-15 15:08:23.382109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f687ccab0ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    with op.batch_alter_table('invoice_entries', schema=None) as batch_op:
        batch_op.alter_column('house_section',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'House Section'"))
        batch_op.alter_column('house_number',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'House Number'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_entries', schema=None) as batch_op:
        batch_op.alter_column('house_number',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'House Number'"))
        batch_op.alter_column('house_section',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'House Section'"))

    op.create_table('payment',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), nullable=False),
    sa.Column('payment_date', sa.DATETIME(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(), nullable=False),
    sa.Column('payment_status', sa.VARCHAR(), nullable=False),
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###
